name: pawrora-kde
description: This is my personal development image, it has kde for desktop and isw for msi notebook fan control.

base-image: ghcr.io/ublue-os/aurora-dx-nvidia
image-version: 41

modules:
  - type: files
    files:
      - source: bin
        destination: /usr/bin
      - source: etc
        destination: /etc
      - source: lib
        destination: /usr/lib

  - type: rpm-ostree

  - type: default-flatpaks
    notify: true

  - type: signing
  - type: fonts
    fonts:
      nerd-fonts:
        - Recursive
