name: pawrora-kde
# description will be included in the image's metadata
description: This is my personal development image, it has kde for desktop and isw for msi notebook fan control.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx-nvidia
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

